# Generated by Django 4.2.3 on 2023-11-07 06:26

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('team_activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamactivitiespost',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='내용'),
        ),
    ]
