# Generated by Django 4.2.3 on 2024-05-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userloginfails_delete_loginfail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginFails',
        ),
    ]
