# Generated by Django 4.2.3 on 2024-04-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
