# Generated by Django 4.2.3 on 2024-03-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecordsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
                ('applicants', models.IntegerField()),
                ('members', models.IntegerField()),
                ('projects', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialActivitiesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='images', verbose_name='image')),
            ],
        ),
    ]
