# Generated by Django 4.2.3 on 2024-03-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecordsInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
                ('applicants', models.IntegerField()),
                ('members', models.IntegerField()),
                ('projects', models.IntegerField()),
            ],
        ),
    ]
