# Generated by Django 4.2.3 on 2024-03-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialactivitiespost',
            name='img',
        ),
    ]
