# Generated by Django 4.2.3 on 2024-03-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activity_records_count',
        ),
        migrations.DeleteModel(
            name='special_activities_tab',
        ),
    ]
