# Generated by Django 4.2.3 on 2024-03-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_specialactivitiespost_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialactivitiespost',
            name='img',
            field=models.ImageField(null=True, upload_to='images', verbose_name='image'),
        ),
    ]
