# Generated by Django 4.2.3 on 2024-03-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_specialactivitiespost_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialactivitiespost',
            old_name='img',
            new_name='photo',
        ),
    ]
