# Generated by Django 4.2.3 on 2023-09-26 14:22

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_advancedassignment_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancedassignment",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name="basicassignment",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
