# Generated by Django 4.2.3 on 2023-09-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_alter_advancedassignment_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicassignment",
            name="file_upload",
            field=models.FileField(default=1, upload_to="uploads/"),
            preserve_default=False,
        ),
    ]
