# Generated by Django 4.2.3 on 2023-11-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0006_advancedassignment_file_upload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicassignment",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
