# Generated by Django 4.2.3 on 2023-11-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0007_basicassignment_modify_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancedassignment",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
