# Generated by Django 4.2.3 on 2024-01-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0008_advancedassignment_modify_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancedassignment",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="basicassignment",
            name="content",
            field=models.TextField(),
        ),
    ]
