# Generated by Django 4.2.4 on 2023-09-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='포스트 제목'),
        ),
    ]
