# Generated by Django 4.2.4 on 2023-09-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_hashtag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
