# Generated by Django 4.2.4 on 2023-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_remove_post_tags_delete_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='동아리 기수'),
        ),
    ]
