# Generated by Django 4.2.4 on 2023-12-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_remove_post_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
    ]
