# Generated by Django 4.2.4 on 2023-12-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0012_alter_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='participant',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='팀원'),
        ),
    ]
