# Generated by Django 4.2.4 on 2024-01-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0013_post_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='generation',
            field=models.PositiveIntegerField(null=True, verbose_name='동아리 기수'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='포스트 제목'),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='연도'),
        ),
    ]
