# Generated by Django 4.2.4 on 2024-01-06 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0016_alter_post_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
    ]
