# Generated by Django 4.2.4 on 2024-01-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0017_remove_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.PositiveIntegerField(default='', null=True, verbose_name='연도'),
        ),
    ]
