# Generated by Django 5.0.4 on 2024-05-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0020_comment_name_comment_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
