# Generated by Django 5.0.4 on 2024-05-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0021_remove_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='연도'),
        ),
    ]
