# Generated by Django 4.2.3 on 2024-05-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0022_remove_comment_profile_image_alter_post_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='포스트 제목'),
        ),
    ]
