# Generated by Django 4.2.3 on 2024-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0023_comment_name_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='작성일시'),
        ),
    ]
