# Generated by Django 4.2.3 on 2024-05-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0024_alter_comment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='작성일시'),
        ),
    ]
