# Generated by Django 4.2.3 on 2024-05-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='instagram_token')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='최종수정일')),
            ],
        ),
    ]
