# Generated by Django 4.2.3 on 2024-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_instagramtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special_activities_tab',
            name='image',
        ),
        migrations.AddField(
            model_name='special_activities_tab',
            name='subtitle',
            field=models.CharField(default='tag', max_length=50, verbose_name='태그'),
        ),
    ]
