# Generated by Django 4.2.3 on 2024-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_remove_special_activities_tab_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_activities_tab',
            name='category',
            field=models.IntegerField(choices=[(0, 'Category 0'), (1, 'Category 1'), (2, 'Category 2')], default=1, verbose_name='이미지'),
        ),
    ]
