# Generated by Django 4.2.3 on 2024-05-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_special_activities_tab_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity_records_count',
            options={'verbose_name': '동아리 활동 기록', 'verbose_name_plural': 'Activity Record'},
        ),
        migrations.AlterField(
            model_name='activity_records_count',
            name='applicants',
            field=models.IntegerField(verbose_name='지원자 수'),
        ),
        migrations.AlterField(
            model_name='activity_records_count',
            name='members',
            field=models.IntegerField(verbose_name='활동 부원 수'),
        ),
        migrations.AlterField(
            model_name='activity_records_count',
            name='years',
            field=models.IntegerField(verbose_name='운영 기간'),
        ),
        migrations.AlterField(
            model_name='special_activities_tab',
            name='category',
            field=models.IntegerField(choices=[(0, 'Get The Flag'), (1, 'networking'), (2, 'Education')], default=1, verbose_name='그림'),
        ),
        migrations.AlterField(
            model_name='special_activities_tab',
            name='subtitle',
            field=models.CharField(default='tag', max_length=50, verbose_name='태그(#)'),
        ),
    ]
