# Generated by Django 4.2.3 on 2024-04-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0002_rentallink_submissionlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("link", models.URLField()),
                ("thumbnail", models.ImageField(upload_to="lecture")),
                ("hashtags", models.ManyToManyField(to="notice.hashtag")),
            ],
        ),
    ]
