# Generated by Django 4.2.3 on 2024-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0004_rename_rental_lecture"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtensionFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MembershipFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
            ],
        ),
    ]
