# Generated by Django 4.2.3 on 2024-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0005_extensionfee_membershipfee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("membership_fee", models.PositiveIntegerField()),
                ("extension_fee", models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="ExtensionFee",
        ),
        migrations.DeleteModel(
            name="MembershipFee",
        ),
    ]
