# Generated by Django 4.2.3 on 2024-03-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="application_link",
            field=models.URLField(verbose_name="지원 링크"),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="end_date",
            field=models.DateField(verbose_name="모집 종료 날짜"),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="start_date",
            field=models.DateField(verbose_name="모집 시작 날짜"),
        ),
    ]
