# Generated by Django 4.2.3 on 2024-03-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0002_alter_recruitment_application_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="application_link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="start_date",
            field=models.DateField(),
        ),
    ]
