# Generated by Django 4.2.4 on 2024-03-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_passed', models.BooleanField(default=False)),
            ],
        ),
    ]
