# Generated by Django 4.2.4 on 2024-04-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_alter_applicant_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='generation',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
