# Generated by Django 4.2.4 on 2024-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_applicant_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='position',
            field=models.CharField(choices=[('기초', '기초'), ('심화', '심화')], default='기초', max_length=10),
        ),
    ]
