# Generated by Django 4.2.4 on 2024-04-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_applicant_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('대면', '대면'), ('비대면', '비대면')], default='대면', max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
