# Generated by Django 4.2.3 on 2024-04-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0010_discord"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leader_contact", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
