# Generated by Django 4.2.4 on 2024-04-06 18:12

from django.db import migrations, models
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0012_contact_delete_leadercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.CharField(max_length=20, validators=[recruit.models.validate_contact], verbose_name='회장단 연락처'),
        ),
    ]
