# Generated by Django 4.2.4 on 2023-09-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_remove_post_tags_delete_hashtag'),
        ('User', '0002_user_profile_image_user_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='volunteer.post', verbose_name='좋아요 누른 Post 목록'),
        ),
    ]
