# Generated by Django 4.2.3 on 2024-05-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_like_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
