# Generated by Django 4.2.3 on 2024-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='메모'),
        ),
    ]
